<!-- Icone de teste -->
<!-- <i class="fas fa-adjust"></i> -->

<div class="container-fluid h-100">
	<div class="row">
		<div class="col-lg banner">
			<p>Banner</p>
		</div>
		<div class="col-lg d-flex justify-content-center align-items-center login">
			<form method="POST" action="/validar" class="mb-3">
				<div class="box_login">
					<label>login:</label>
					<input type="text" name="login" placeholder="login ou email" />
				</div>
				<div class="box_senha">
					<label>senha:</label>
					<input type="password" name="senha" placeholder="mínino 6 caracteres" />
				</div>
				<div class="box_entrar_esqueci">
					<button type="submit">entrar</button>
					<a href="/recuperar_conta" class="recuperar">recuperar conta</a>
				</div>
				<a href="/cadastrar" class="cadastrar">cadastrar</a>
			</form>
	</div>
</div>