<div class="container">
    <div class="row">
        <div class="col">
            <form method="POST" action="/editar_dados" enctype="multipart/form-data">
                <div class="box_imagem">
                    <label>foto de perfil:</label>
                    <input type="file" name="foto" />
                </div>
                <div class="box_nascimento">
					<label>data de nascimento:</label>
					<input type="date" name="nascimento" value="<?= $this->view->usuario['nascimento']; ?>" />
				</div>
				<div class="box_genero">
					<fieldset><label>gênero:</label>
						<label for="masculino">masculino</label>
						<input type="radio" name="genero" value="masculino" id="masculino" <?php $this->view->usuario['genero']=='masculino'? print('checked'):''; ?> />

						<label for="feminino">feminino</label>
						<input type="radio" name="genero" value="feminino" id="feminino" <?php $this->view->usuario['genero']=='feminino'? print('checked'):''; ?> />

						<label for="outro">outro</label>
						<input type="radio" name="genero" value="outro" id="outro" <?php $this->view->usuario['genero']=='outro'? print('checked'):''; ?>/>
					</fieldset>
				</div>
				<div class="box_tempo">
					<label>tempo de prática em kinesis:</label>
					<input type="date" name="comeco" value="<?= $this->view->usuario['comeco']; ?>" />
				</div>
				<div class="box_login">
					<label>login:</label>
					<input type="text" name="login" value="<?= $this->view->usuario['nick']; ?>" maxlength="10" />
				</div>
				<div class="box_email">
					<label>email:</label>
					<input type="text" name="email" value="<?= $this->view->usuario['email']; ?>" maxlength="40" />
				</div><div class="box_primaria">
                <label>Primária:</label>
                <select name="primaria">
                    <option value="Aerokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='AeroKinesis'?'selected':''; ?> >Aerokinesis</option>
                    <option value="Biokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Biokinesis'?'selected':''; ?> >Biokinesis</option>
                    <option value="Criokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Criokinesis'?'selected':''; ?> >Criokinesis</option>
                    <option value="Chronokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Chronokinesis'?'selected':''; ?> >Chronokinesis</option>
                    <option value="Electrokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Electrokinesis'?'selected':''; ?> >Electrokinesis</option>
                    <option value="Geokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Geokinesis'?'selected':''; ?> >Geokinesis</option>
                    <option value="Hidrokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Hidrokinesis'?'selected':''; ?> >Hidrokinesis</option>
                    <option value="Luminokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Luminokinese'?'selected':''; ?> >Luminokinese</option>
                    <option value="Pyrokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Pyrokinese'?'selected':''; ?> >Pyrokinese</option>
                    <option value="Psicokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Psicokinese'?'selected':''; ?> >Psicokinese</option>
                    <option value="Umbrakinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Umbrakinesis'?'selected':''; ?> >Umbrakinesis </option>
                    <option value="Atmokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Atmokinese'?'selected':''; ?> >Atmokinese</option>
                    <option value="Telecinese" <?= $this->view->kinesis_alt[0]['primaria']=='Telecinese'?'selected':''; ?> >Telecinese</option>
                </select>
            </div>
            <div class="box_secundaria">
            <?php
            // verificar se kinesis é primária com js(já verificado com php)!!


                $kinesis = ['nenhum', 'Aerokinesis', 'Biokinesis', 'Criokinesis', 'Chronokinesis', 'Electrokinesis', 'Geokinesis', 'Hidrokinesis', 'Luminokinese', 'Pyrokinese', 'Psicokinese', 'Umbrakinesis', 'Atmokinese', 'Telecinese'];

                array_shift($this->view->kinesis_alt);

                foreach($kinesis as $kinese){
                    ?>
                        <label for='<?= $kinese; ?>'><?= $kinese; ?></label>
                        <input type='checkbox' name='secundaria[]' value='<?= $kinese; ?>' id='<?= $kinese; ?>' 
                        <?php foreach($this->view->kinesis_alt as $dados_kinesis){ if($dados_kinesis['secundaria'] == $kinese){ echo "checked"; } }?> /> <?php } ?>
            </div>
                <div class="box_submit">
                    <button type="submit">alterar</button>
                </div>
				<?php
					if(isset($_GET['msg'])){
						if($_GET['msg'] == 'nickExiste'){
							echo '<small class="text-danger">login já existe</small>';
						}
						if($_GET['msg'] == 'emailExiste'){
							echo '<small class="text-danger">email já existe</small>';
                        }
                        if($_GET['msg'] == 'kinesis_iguais'){
                            echo '<small class="text-danger">kinese secundária igual a primária</small>';
                        }
					}
				?>
            </form>
			<a href="/painel">voltar</a>
        </div>
    </div>
</div>