<div class="container">
    <div class="row">
        <div class="col">
            <form method="POST" action="/editar_dados" enctype="multipart/form-data" class="form-group">
                <div class="box_imagem form-group">
                    <label>Imagem de perfil:</label>
                    
                    <label class="label_foto"  for="foto"><i class="fas fa-street-view icone_foto"></i></label>
                    <input type="file" id="foto" name="foto" />

                </div>
                <div class="box_nascimento form-group">
                    <?php
                        $partes_data = explode('/', $this->view->usuario['nascimento']);

                        $americano_data = new DateTime();
                        $americano_data->setDate($partes_data[2], $partes_data[1], $partes_data[0])
                    ?>
					<label>Data de nascimento:</label>
					<input type="date" name="nascimento" value="<?= $americano_data->format('Y-m-d'); ?>" class="form-control" />
				</div>
				<div class="box_genero form-group">
					<label>Gênero:</label>
                    <div class="form-check">
                        <input type="radio" name="genero" value="masculino" id="masculino" class="form-check-input" <?php $this->view->usuario['genero']=='masculino'? print('checked'):''; ?> />
                        <label for="masculino" class="form-check-label">masculino</label>
                    </div>
                    <div class="form-check">
                        <input type="radio" name="genero" value="feminino" id="feminino" class="form-check-input" <?php $this->view->usuario['genero']=='feminino'? print('checked'):''; ?> />
                        <label for="feminino" class="form-check-label">feminino</label>
                    </div>
                    <div class="form-check">
                        <input type="radio" name="genero" value="outro" id="outro" class="form-check-input" <?php $this->view->usuario['genero']=='outro'? print('checked'):''; ?>/>
                        <label for="outro" class="form-check-label">outro</label>
                    </div>
				</div>
				<div class="box_tempo form-group">
                    <?php
                        $partes_data = explode('/', $this->view->usuario['comeco']);
                        
                        $americano_data->setDate($partes_data[2], $partes_data[1], $partes_data[0])
                    ?>
					<label>Tempo de prática em kinesis:</label>
					<input type="date" name="comeco" class="form-control" value="<?= $americano_data->format('Y-m-d'); ?>" />
				</div>
				<div class="box_login form-group">
					<label>Login:</label>
					<input type="text" name="login" class="form-control" value="<?= $this->view->usuario['nick']; ?>" maxlength="10" />
				</div>
				<div class="box_email form-group">
					<label>Email:</label>
					<input type="text" name="email" class="form-control" value="<?= $this->view->usuario['email']; ?>" maxlength="40" />
				</div><div class="box_primaria form-group">
                <label>Primária:</label>
                <select name="primaria" class="form-control">
                    <option value="Aerokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='AeroKinesis'?'selected':''; ?> >Aerokinesis</option>
                    <option value="Biokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Biokinesis'?'selected':''; ?> >Biokinesis</option>
                    <option value="Criokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Criokinesis'?'selected':''; ?> >Criokinesis</option>
                    <option value="Chronokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Chronokinesis'?'selected':''; ?> >Chronokinesis</option>
                    <option value="Electrokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Electrokinesis'?'selected':''; ?> >Electrokinesis</option>
                    <option value="Geokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Geokinesis'?'selected':''; ?> >Geokinesis</option>
                    <option value="Hidrokinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Hidrokinesis'?'selected':''; ?> >Hidrokinesis</option>
                    <option value="Luminokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Luminokinese'?'selected':''; ?> >Luminokinese</option>
                    <option value="Pyrokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Pyrokinese'?'selected':''; ?> >Pyrokinese</option>
                    <option value="Psicokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Psicokinese'?'selected':''; ?> >Psicokinese</option>
                    <option value="Umbrakinesis" <?= $this->view->kinesis_alt[0]['primaria']=='Umbrakinesis'?'selected':''; ?> >Umbrakinesis </option>
                    <option value="Atmokinese" <?= $this->view->kinesis_alt[0]['primaria']=='Atmokinese'?'selected':''; ?> >Atmokinese</option>
                    <option value="Telecinese" <?= $this->view->kinesis_alt[0]['primaria']=='Telecinese'?'selected':''; ?> >Telecinese</option>
                </select>
            </div>
            <div class="box_secundaria form-group">
                <label>Secundária:</label>
            <?php
            // verificar se kinesis é primária com js(já verificado com php)!!


                $kinesis = ['nenhum', 'Aerokinesis', 'Biokinesis', 'Criokinesis', 'Chronokinesis', 'Electrokinesis', 'Geokinesis', 'Hidrokinesis', 'Luminokinese', 'Pyrokinese', 'Psicokinese', 'Umbrakinesis', 'Atmokinese', 'Telecinese'];

                array_shift($this->view->kinesis_alt);

                foreach($kinesis as $kinese){
                    ?>
                    <div class='form-check'>
                        <input type='checkbox' name='secundaria[]' class='form-control-input' value='<?= $kinese; ?>' id='<?= $kinese; ?>' 
                        <?php foreach($this->view->kinesis_alt as $dados_kinesis){ if($dados_kinesis['secundaria'] == $kinese){ echo "checked"; } }?> />
                        <label for='<?= $kinese; ?>' class='form-control-label'><?= $kinese; ?></label>
                    </div> 
                <?php } ?>
            </div>
                <div class="box_submit">
                    <button type="submit" class="btn btn-success">alterar</button>
                </div>
				<?php
					if(isset($_GET['msg'])){
						if($_GET['msg'] == 'nickExiste'){
							echo '<small class="text-danger">login já existe</small>';
						}
						if($_GET['msg'] == 'emailExiste'){
							echo '<small class="text-danger">email já existe</small>';
                        }
                        if($_GET['msg'] == 'kinesis_iguais'){
                            echo '<small class="text-danger">kinese secundária igual à primária</small>';
                        }
                        // recebendo no painel
                        if($_GET['msg'] == 'formato_bloqueado'){
                            echo '<small class="text-danger">formato de arquivo não suportado</small>';
                        }
                        if($_GET['msg'] == 'tamanho_exedido'){
                            echo '<small class="text-danger">tamanho do arquivo exedido</small>';
                        }
                        // recebendo no painel
					}
				?>
            </form>
			<a href="/painel" class="btn btn-info">voltar</a>
        </div>
    </div>
</div>