<div class="container-fluid painel">
    <div class="row">
        <div class="col">
            <header class="bg-success">
                <nav>
                    <a href="/sair" class="text-light" style="width:10%" title="sair"><i class="fas fa-power-off"></i></a><br/>
                    <span><img src="img/sistema/logo_ganko.png" alt="logo ganko" class="img-fluid logo" /></span>
                    <a href="/perfil" class="text-light" style="width:5%" title="perfil"><i class="fas fa-user-circle"></i></a><br/>
                    <a href="/adicionar_amigos" class="text-light ml-3" style="width:5%" title="amigos"><i class="fas fa-user-friends"></i></a>
                </nav>
            </header>
            <div id="mySidenav" class="sidenav bg-success">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                
                <span><img src="img/sistema/logo_ganko.png" alt="logo ganko" class="img-fluid logo" /></span>
                <div class="link_a">
                    <a href="/sair" class="text-light nav_a" title="sair"><i class="fas fa-power-off"></i> encerrar sessão</a><br/>
                    <a href="/perfil" class="text-light nav_a" title="perfil"><i class="fas fa-user-circle"></i> perfil</a><br/>
                    <a href="/adicionar_amigos" class="text-light nav_a" title="amigos"><i class="fas fa-user-friends"></i> adicionar amigos</a>
                </div>
            </div>
            <span class="bg-success open_resp" style="font-size:30px;cursor:pointer" onclick="openNav()">
                <img src="img/sistema/logo_ganko.png" alt="logo ganko" class="img-fluid logo" />
                <p>&#9776;</p>
            </span>

            <script>
                var x, i;

                function openNav(){
                    document.getElementById("mySidenav").style.width = "100%";

                    x = document.querySelectorAll(".nav_a")
                    for(i=0; i<x.length; i++){
                        x[i].style.display = "block";
                    }
                }
                function closeNav(){
                    document.getElementById("mySidenav").style.width = "0%";

                    x = document.querySelectorAll(".nav_a")
                    for(i=0; i<x.length; i++){
                        x[i].style.display = "none";
                    }
                }
            </script>

            <?php
                if(isset($_GET['msg'])){
                    print("<div id='content-modal' class='w-50 content-modal'>");
                        print("<button id='close' class='close' onclick='return fechar()' >&times;</button>");
                        if($_GET['msg'] == 'postado'){
                            echo "<p class='msg'>Postagem concluída.</p>";
                        }
                        if($_GET['msg'] == 'adicionar_kinese'){
                            echo "<p class='msg'>Antes de alterar seus dados informe suas kinesis.</p>";
                        }
                        if($_GET['msg'] == 'formato_bloqueado'){
                            print("<p class='msg'>Formato de arquivo não suportado.</p>");
                        }
                        if($_GET['msg'] == 'tamanho_exedido'){
                            print("<p class='msg'>Tamanho de arquivo exedido (5mb).</p>");
                        }
                        if($_GET['msg'] == 'postVazio'){
                            print("<p class='msg'>Post vazio.</p>");
                        }
                        if($_GET['msg'] == 'kinesis_iguais'){
                            print("<p class='msg'>Kinese primária idêntica à secundária.</p>");
                        }
                    print("</div>");
                }
            ?>

            <div class="formularios">
                <?php
                    if(isset($this->view->validaFoto)){
                        if($this->view->validaFoto){
                ?>
                            <form method="POST" class="add_imagem" action="/add_imagem" enctype="multipart/form-data">
                                <h1 class="display-4">Adicione uma imagem de perfil:</h1>
                                <div class="box_imagem">
                                    <label class="label_foto"  for="foto"><i class="fas fa-street-view icone_foto"></i></label>
                                    <input type="file" id="foto" name="foto" />

                                    <input type="submit" class="btn btn-outline-light" value="upload" name="submit">
                                </div>
                                <div class="box_msg">
                                    <?php
                                        if(isset($_GET['stt_upload'])){
                                            if($_GET['stt_upload'] == 'formato_bloqueado'){
                                                print("<p class='text-danger'>formato de arquivo não suportado</p>");
                                            }if($_GET['stt_upload'] == 'tamanho_exedido'){
                                                print("<p class='text-danger'>tamanho de arquivo exedido(5mb)</p>");
                                            }
                                        }
                                    ?>
                                </div>
                            </form>
                <?php
                        }
                    }
                ?>


                <?php
                    if(isset($this->view->criarKinesis)){
                        if($this->view->criarKinesis){ 
                ?>
                    
                        <form method="POST" action="/addKinesis" class="form-group add_kinesis">
                            <div class="form-group box_primaria">
                                <label class="titulo_kinesis">Primária:</label>
                                <select name="primaria" class="form-control op_pri">
                                    <option value="nenhum">nenhum</option>
                                    <option value="Aerokinesis">Aerokinesis</option>
                                    <option value="Biokinesis">Biokinesis</option>
                                    <option value="Criokinesis">Criokinesis</option>
                                    <option value="Chronokinesis">Chronokinesis</option>
                                    <option value="Electrokinesis">Electrokinesis</option>
                                    <option value="Geokinesis">Geokinesis</option>
                                    <option value="Hidrokinesis">Hidrokinesis</option>
                                    <option value="Luminokinese">Luminokinese</option>
                                    <option value="Pyrokinese">Pyrokinese</option>
                                    <option value="Psicokinese">Psicokinese</option>
                                    <option value="Umbrakinesis">Umbrakinesis </option>
                                    <option value="Atmokinese">Atmokinese</option>
                                    <option value="Telecinese">Telecinese</option>
                                </select>
                            </div>
                            <div class="form-group box_secundaria">
                                <label class="titulo_kinesis">Secundária:</label>

                                <div class="op_sec">
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Nenhum" id="nenhum" class="form-check-input">
                                        <label for="nenhum" class="form-check-label">Nenhum</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Aerokinesis" id="Aerokinesis" class="form-check-input">
                                        <label for="Aerokinesis" class="form-check-label">Aerokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Biokinesis" id="Biokinesis" class="form-check-input">
                                        <label for="Biokinesis" class="form-check-label">Biokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Criokinesis" id="Criokinesis" class="form-check-input">
                                        <label for="Criokinesis" class="form-check-label">Criokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Chronokinesis" id="Chronokinesis" class="form-check-input">
                                        <label for="Chronokinesis" class="form-check-label">Chronokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Electrokinesis" id="Electrokinesis" class="form-check-input">
                                        <label for="Electrokinesis" class="form-check-label">Electrokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Geokinesis" id="Geokinesis" class="form-check-input">
                                        <label for="Geokinesis" class="form-check-label">Geokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Hidrokinesis" id="Hidrokinesis" class="form-check-input">
                                        <label for="Hidrokinesis" class="form-check-label">Hidrokinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Luminokinese" id="Luminokinese" class="form-check-input">
                                        <label for="Luminokinese" class="form-check-label">Luminokinese</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Pyrokinese" id="Pyrokinese" class="form-check-input">
                                        <label for="Pyrokinese" class="form-check-label">Pyrokinese</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Psicokinese" id="Psicokinese" class="form-check-input">
                                        <label for="Psicokinese" class="form-check-label">Psicokinese</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Umbrakinesis" id="Umbrakinesis" class="form-check-input">
                                        <label for="Umbrakinesis" class="form-check-label">Umbrakinesis</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Atmokinese" id="Atmokinese" class="form-check-input">
                                        <label for="Atmokinese" class="form-check-label">Atmokinese</label>
                                    </div>
                            
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" name="secundaria[]" value="Telecinese" id="Telecinese" class="form-check-input">
                                        <label for="Telecinese" class="form-check-label">Telecinese</label>
                                    </div>
                                </div>
                            </div>
                            <div class="box_submit">
                                <button type="submit" class="btn btn-outline-light">enviar</button>
                            </div>
                        </form>
                <?php 
                        }
                    } 
                ?>
            </div>

            <div class="conteudo">
                <div class="post">
                    <form method="POST" action="/set_post" enctype="multipart/form-data">
                        <div class="box_texto">
                            <textarea name="post_texto"></textarea>
                        </div>
                        <div class="box_arquivo">
                            <label for="post_arquivo" class="icones_arquivo">
                                <i class="fas fa-images"></i>
                                <i class="fas fa-video"></i>
                                <i class="fas fa-volume-up"></i>
                            </label>
                            <input type="file" name="post_arquivo" id="post_arquivo" style="display: none;" />
                        </div>
                        <div class="box_submit">
                            <button type="submit">postar</button>
                        </div>
                    </form>
                </div>
                <div class="postagens">
                    <?php
                        foreach($this->view->postagens AS $postagem){
                            $extensao = $postagem['tipo'];

                            print("<div class='postagem'>");
                            
                                if($extensao == 'image/jpg' || $extensao == 'image/jpeg' || $extensao == 'image/gif' || $extensao == 'image/png'){
                                    print("<img src='post/".$postagem['arquivo']."' class='arquivo_postagem' />");
                                }
                                if($extensao == 'video/mp4' || $extensao == 'video/webm' || $extensao == 'video/svg'){
                                    print("
                                        <video class='arquivo_postagem' controls>
                                            <source src='post/".$postagem['arquivo']."' />Seu navegador não suporta o tipo do vídeo
                                        </video>");
                                }
                                if($extensao == 'audio/mp3' || $extensao == 'audio/wave' || $extensao == 'audio/wav'){
                                    print("
                                        <audio class='arquivo_postagem' controls>
                                            <source src='post/".$postagem['arquivo']."' class='arquivo_postagem' />Seu navedador não suporta o tipo do audio
                                        </audio>
                                    ");
                                }
                                print("<p class='texto_postagem'>".$postagem['texto']."</p>
                                <a href='/perfil' class='link_usuario'>
                                    <img src='img/perfil/".$postagem['foto_usuario']."' class='imagem_usuario_publicacao' />
                                    <p class='nome_usuario'>".$postagem['nome_usuario']."</p>
                                </a>
                            </div>");
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>