<div class="container-fluid">
    <div class="row">
        <div class="col">

        </div>
        <div class="col">
            <p><?= $this->view->dados_usuario['nome']; ?></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
        </div>
        <div class="col">
            
        </div>
    </div>
</div>