<div class="container-fluid">
    <div class="row">
        <div class="col">
            <?php
                if(isset($_GET['msg'])){
                    if($_GET['msg'] == 'dadosAlt'){
                        echo 'dados alterados';
                    }
                }
            ?>
			<a href="/painel">voltar</a>
            <a href="/deletar_conta">deletar conta</a>
        </div>
        <div class="col">
            <img src="img/perfil/<?= $this->view->dados_usuario['foto']; ?>" class="img-fluid" />
            <p><?= $this->view->dados_usuario['nome']; ?></p>
            <p><?= $this->view->dados_usuario['sobrenome']; ?></p>
            <p><?= $this->view->dados_usuario['nascimento']; ?></p>
            <p><?= $this->view->dados_usuario['genero']; ?></p>
            <p><?= $this->view->dados_usuario['comeco']; ?></p>
            <p><?= $this->view->dados_usuario['nick']; ?></p>
            <p><?= $this->view->dados_usuario['email']; ?></p>
            <?php
                if($this->view->kinesis_existem){
                    print("<p>".$this->view->primaria."</p>");

                    foreach($this->view->secundaria as $secundarias){
                        print("<p>".$secundarias['secundaria']."</p>");
                    }
                }
            ?>
            <a href="/alterar_dados">alterar dados</a>
        </div>
        <div class="col">
            
        </div>
    </div>
</div>